import { Buffer } from "node:buffer";
import {
  intakeToEventFacts,
  parseEventFactsDocument,
  serializeStoredIntakePayload,
  type EventFactsDocument
} from "@/lib/event-facts";
import type { IntakeInput } from "@/lib/schemas";

export type DemoScenario = {
  slug:
    | "private-property-punk-show"
    | "food-truck-local-art-market"
    | "small-outdoor-community-event"
    | "critical-missing-information"
    | "unsupported-jurisdiction"
    | "threshold-boundary-event";
  title: string;
  summary: string;
  whyItMatters: string;
  intake: IntakeInput;
  featuredPath: "guided" | "describe";
  eventFacts?: EventFactsDocument;
};

const scenarios: DemoScenario[] = [
  {
    slug: "private-property-punk-show",
    title: "Fictional demo: Private-property punk show",
    summary:
      "A one-night Phoenix punk show in a parking lot with amplified sound, a temporary stage, and ticket sales.",
    whyItMatters:
      "Shows route stacking for venue type, sound, temporary setup, and public attendance.",
    featuredPath: "describe",
    intake: {
      eventName: "Warehouse Sparks Fest",
      city: "phoenix",
      county: "Maricopa County",
      useCase: "private-property-parking-lot-event",
      eventType: "music-art-event",
      propertyUse: "parking-lot",
      expectedAttendance: 280,
      vendorCount: 6,
      eventDate: "2026-10-17",
      recurrence: "one-time",
      hasFood: false,
      hasFoodTruck: false,
      hasRetailSales: true,
      hasAlcohol: false,
      hasAmplifiedSound: true,
      hasTemporaryStructure: true,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: false,
      foodRequiresTemperatureControl: false,
      foodSampling: false,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: false,
      commissaryOrBaseOfOperations: false,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: false,
      tentSizeRange: "none",
      temporaryStageOrPlatform: true,
      cookingHeatSource: false,
      propaneOrFuelUse: false,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: true,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: true,
      banners: true,
      ticketedEvent: true,
      admissionFee: true,
      publicAdvertising: true,
      cityParkOrFacility: false,
      privateProperty: true,
      publicProperty: false,
      venueOrPropertyOwnerPermission: true,
      indoorOrOutdoor: "outdoor",
      recurringEvent: false
    }
  },
  {
    slug: "food-truck-local-art-market",
    title: "Fictional demo: Food-truck and local-art market",
    summary:
      "A Tempe outdoor market with food trucks, local art vendors, retail sales, and light promotion.",
    whyItMatters:
      "Shows city, county, and state guidance stacking for food, vendors, and retail.",
    featuredPath: "guided",
    intake: {
      eventName: "Sunset Local Art Market",
      city: "tempe",
      county: "Maricopa County",
      useCase: "food-truck-temporary-food-vendor",
      eventType: "outdoor-market",
      propertyUse: "public-property",
      expectedAttendance: 175,
      vendorCount: 14,
      eventDate: "2026-09-19",
      recurrence: "one-time",
      hasFood: true,
      hasFoodTruck: true,
      hasRetailSales: true,
      hasAlcohol: false,
      hasAmplifiedSound: false,
      hasTemporaryStructure: false,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: true,
      foodRequiresTemperatureControl: true,
      foodSampling: true,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: true,
      commissaryOrBaseOfOperations: true,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: true,
      tentSizeRange: "small-under-400-sq-ft",
      temporaryStageOrPlatform: false,
      cookingHeatSource: true,
      propaneOrFuelUse: true,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: false,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: true,
      banners: true,
      ticketedEvent: false,
      admissionFee: false,
      publicAdvertising: true,
      cityParkOrFacility: false,
      privateProperty: false,
      publicProperty: true,
      venueOrPropertyOwnerPermission: true,
      indoorOrOutdoor: "outdoor",
      recurringEvent: false
    }
  },
  {
    slug: "small-outdoor-community-event",
    title: "Fictional demo: Small outdoor community event",
    summary:
      "A small Mesa neighborhood gathering with music, tables, and volunteer hosts.",
    whyItMatters:
      "Shows a lower-complexity route and helps testers explain the product quickly.",
    featuredPath: "guided",
    intake: {
      eventName: "Neighborhood Glow Night",
      city: "mesa",
      county: "Maricopa County",
      useCase: "small-outdoor-music-art-event",
      eventType: "community-gathering",
      propertyUse: "park-or-plaza",
      expectedAttendance: 90,
      vendorCount: 2,
      eventDate: "2026-09-05",
      recurrence: "one-time",
      hasFood: false,
      hasFoodTruck: false,
      hasRetailSales: false,
      hasAlcohol: false,
      hasAmplifiedSound: true,
      hasTemporaryStructure: false,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: false,
      foodRequiresTemperatureControl: false,
      foodSampling: false,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: false,
      commissaryOrBaseOfOperations: false,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: true,
      tentSizeRange: "small-under-400-sq-ft",
      temporaryStageOrPlatform: false,
      cookingHeatSource: false,
      propaneOrFuelUse: false,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: false,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: false,
      banners: false,
      ticketedEvent: false,
      admissionFee: false,
      publicAdvertising: true,
      cityParkOrFacility: true,
      privateProperty: false,
      publicProperty: true,
      venueOrPropertyOwnerPermission: true,
      indoorOrOutdoor: "outdoor",
      recurringEvent: false
    }
  },
  {
    slug: "critical-missing-information",
    title: "Fictional demo: Event with critical missing information",
    summary:
      "A Chandler event concept with important unknowns left unresolved to show review friction safely.",
    whyItMatters:
      "Shows how Gatherwise keeps uncertainty visible instead of pretending the route is settled.",
    featuredPath: "guided",
    intake: {
      eventName: "Late Shift Pop-Up",
      city: "chandler",
      county: "Maricopa County",
      useCase: "small-outdoor-music-art-event",
      eventType: "vendor-pop-up",
      propertyUse: "private-property",
      expectedAttendance: 120,
      vendorCount: 4,
      eventDate: "2026-11-01",
      recurrence: "one-time",
      hasFood: false,
      hasFoodTruck: false,
      hasRetailSales: true,
      hasAlcohol: false,
      hasAmplifiedSound: false,
      hasTemporaryStructure: false,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: false,
      foodRequiresTemperatureControl: false,
      foodSampling: false,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: false,
      commissaryOrBaseOfOperations: false,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: false,
      tentSizeRange: "not-sure",
      temporaryStageOrPlatform: false,
      cookingHeatSource: false,
      propaneOrFuelUse: false,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: false,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: false,
      banners: false,
      ticketedEvent: false,
      admissionFee: false,
      publicAdvertising: false,
      cityParkOrFacility: false,
      privateProperty: true,
      publicProperty: false,
      venueOrPropertyOwnerPermission: false,
      indoorOrOutdoor: "not-sure",
      recurringEvent: false
    },
    eventFacts: parseEventFactsDocument({
      ...intakeToEventFacts({
        eventName: "Late Shift Pop-Up",
        city: "chandler",
        county: "Maricopa County",
        useCase: "small-outdoor-music-art-event",
        eventType: "vendor-pop-up",
        propertyUse: "private-property",
        expectedAttendance: 120,
        vendorCount: 4,
        eventDate: "2026-11-01",
        recurrence: "one-time",
        hasFood: false,
        hasFoodTruck: false,
        hasRetailSales: true,
        hasAlcohol: false,
        hasAmplifiedSound: false,
        hasTemporaryStructure: false,
        hasGenerator: false,
        hasOpenFlame: false,
        hasStreetSidewalkOrParkingImpact: false,
        foodIsPrepackaged: false,
        foodIsOpenOrPreparedOnSite: false,
        foodRequiresTemperatureControl: false,
        foodSampling: false,
        drinksWithIceOrGarnish: false,
        foodTruckOrMobileFoodUnit: false,
        commissaryOrBaseOfOperations: false,
        believesFoodExemptionMayApply: false,
        tentOrCanopy: false,
        tentSizeRange: "not-sure",
        temporaryStageOrPlatform: false,
        cookingHeatSource: false,
        propaneOrFuelUse: false,
        streetClosure: false,
        sidewalkUseOrClosure: false,
        parkingLotUse: false,
        parkingSpacesBlocked: false,
        trafficControlNeeded: false,
        rightOfWayUse: false,
        alcoholPresent: false,
        alcoholSold: false,
        alcoholServedFree: false,
        alcoholByob: false,
        alcoholOnPublicProperty: false,
        temporarySignage: false,
        banners: false,
        ticketedEvent: false,
        admissionFee: false,
        publicAdvertising: false,
        cityParkOrFacility: false,
        privateProperty: true,
        publicProperty: false,
        venueOrPropertyOwnerPermission: false,
        indoorOrOutdoor: "not-sure",
        recurringEvent: false
      }),
      facts: intakeToEventFacts({
        eventName: "Late Shift Pop-Up",
        city: "chandler",
        county: "Maricopa County",
        useCase: "small-outdoor-music-art-event",
        eventType: "vendor-pop-up",
        propertyUse: "private-property",
        expectedAttendance: 120,
        vendorCount: 4,
        eventDate: "2026-11-01",
        recurrence: "one-time",
        hasFood: false,
        hasFoodTruck: false,
        hasRetailSales: true,
        hasAlcohol: false,
        hasAmplifiedSound: false,
        hasTemporaryStructure: false,
        hasGenerator: false,
        hasOpenFlame: false,
        hasStreetSidewalkOrParkingImpact: false,
        foodIsPrepackaged: false,
        foodIsOpenOrPreparedOnSite: false,
        foodRequiresTemperatureControl: false,
        foodSampling: false,
        drinksWithIceOrGarnish: false,
        foodTruckOrMobileFoodUnit: false,
        commissaryOrBaseOfOperations: false,
        believesFoodExemptionMayApply: false,
        tentOrCanopy: false,
        tentSizeRange: "not-sure",
        temporaryStageOrPlatform: false,
        cookingHeatSource: false,
        propaneOrFuelUse: false,
        streetClosure: false,
        sidewalkUseOrClosure: false,
        parkingLotUse: false,
        parkingSpacesBlocked: false,
        trafficControlNeeded: false,
        rightOfWayUse: false,
        alcoholPresent: false,
        alcoholSold: false,
        alcoholServedFree: false,
        alcoholByob: false,
        alcoholOnPublicProperty: false,
        temporarySignage: false,
        banners: false,
        ticketedEvent: false,
        admissionFee: false,
        publicAdvertising: false,
        cityParkOrFacility: false,
        privateProperty: true,
        publicProperty: false,
        venueOrPropertyOwnerPermission: false,
        indoorOrOutdoor: "not-sure",
        recurringEvent: false
      }).facts.map((fact) =>
        ["venueOrPropertyOwnerPermission", "indoorOrOutdoor", "tentSizeRange"].includes(fact.key)
          ? { ...fact, status: "unknown", value: null }
          : fact
      )
    })
  },
  {
    slug: "unsupported-jurisdiction",
    title: "Fictional demo: Unsupported jurisdiction",
    summary:
      "A Nevada event used to show a safe refusal instead of unsupported guidance.",
    whyItMatters:
      "Shows the product boundary clearly and avoids pretending unsupported geography is verified.",
    featuredPath: "guided",
    intake: {
      eventName: "Desert Alley Night Fair",
      city: "phoenix",
      county: "Maricopa County",
      useCase: "small-outdoor-music-art-event",
      eventType: "community-gathering",
      propertyUse: "public-property",
      expectedAttendance: 160,
      vendorCount: 8,
      eventDate: "2026-10-03",
      recurrence: "one-time",
      hasFood: true,
      hasFoodTruck: true,
      hasRetailSales: true,
      hasAlcohol: false,
      hasAmplifiedSound: true,
      hasTemporaryStructure: false,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: true,
      foodRequiresTemperatureControl: true,
      foodSampling: false,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: true,
      commissaryOrBaseOfOperations: true,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: false,
      tentSizeRange: "none",
      temporaryStageOrPlatform: false,
      cookingHeatSource: false,
      propaneOrFuelUse: false,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: false,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: false,
      banners: false,
      ticketedEvent: false,
      admissionFee: false,
      publicAdvertising: true,
      cityParkOrFacility: false,
      privateProperty: false,
      publicProperty: true,
      venueOrPropertyOwnerPermission: true,
      indoorOrOutdoor: "outdoor",
      recurringEvent: false
    },
    eventFacts: parseEventFactsDocument({
      ...intakeToEventFacts({
        eventName: "Desert Alley Night Fair",
        city: "phoenix",
        county: "Maricopa County",
        useCase: "small-outdoor-music-art-event",
        eventType: "community-gathering",
        propertyUse: "public-property",
        expectedAttendance: 160,
        vendorCount: 8,
        eventDate: "2026-10-03",
        recurrence: "one-time",
        hasFood: true,
        hasFoodTruck: true,
        hasRetailSales: true,
        hasAlcohol: false,
        hasAmplifiedSound: true,
        hasTemporaryStructure: false,
        hasGenerator: false,
        hasOpenFlame: false,
        hasStreetSidewalkOrParkingImpact: false,
        foodIsPrepackaged: false,
        foodIsOpenOrPreparedOnSite: true,
        foodRequiresTemperatureControl: true,
        foodSampling: false,
        drinksWithIceOrGarnish: false,
        foodTruckOrMobileFoodUnit: true,
        commissaryOrBaseOfOperations: true,
        believesFoodExemptionMayApply: false,
        tentOrCanopy: false,
        tentSizeRange: "none",
        temporaryStageOrPlatform: false,
        cookingHeatSource: false,
        propaneOrFuelUse: false,
        streetClosure: false,
        sidewalkUseOrClosure: false,
        parkingLotUse: false,
        parkingSpacesBlocked: false,
        trafficControlNeeded: false,
        rightOfWayUse: false,
        alcoholPresent: false,
        alcoholSold: false,
        alcoholServedFree: false,
        alcoholByob: false,
        alcoholOnPublicProperty: false,
        temporarySignage: false,
        banners: false,
        ticketedEvent: false,
        admissionFee: false,
        publicAdvertising: true,
        cityParkOrFacility: false,
        privateProperty: false,
        publicProperty: true,
        venueOrPropertyOwnerPermission: true,
        indoorOrOutdoor: "outdoor",
        recurringEvent: false
      }),
      jurisdiction: {
        code: "las-vegas",
        jurisdictionCode: null,
        city: "Las Vegas",
        county: "Clark County",
        state: "NV",
        label: "Las Vegas, Nevada",
        supported: false
      },
      locationScope: {
        cityCode: "las-vegas",
        cityName: "Las Vegas",
        county: "Clark County",
        propertyUse: "public-property"
      }
    })
  },
  {
    slug: "threshold-boundary-event",
    title: "Fictional demo: Threshold-boundary event",
    summary:
      "A Scottsdale event set near an attendance threshold to support route comparison in the simulator.",
    whyItMatters:
      "Helps recruiters and participants see how one detail can change the deterministic route.",
    featuredPath: "guided",
    intake: {
      eventName: "Threshold Line Block Party",
      city: "scottsdale",
      county: "Maricopa County",
      useCase: "small-outdoor-music-art-event",
      eventType: "community-gathering",
      propertyUse: "public-property",
      expectedAttendance: 99,
      vendorCount: 3,
      eventDate: "2026-10-24",
      recurrence: "one-time",
      hasFood: false,
      hasFoodTruck: false,
      hasRetailSales: false,
      hasAlcohol: false,
      hasAmplifiedSound: true,
      hasTemporaryStructure: true,
      hasGenerator: false,
      hasOpenFlame: false,
      hasStreetSidewalkOrParkingImpact: false,
      foodIsPrepackaged: false,
      foodIsOpenOrPreparedOnSite: false,
      foodRequiresTemperatureControl: false,
      foodSampling: false,
      drinksWithIceOrGarnish: false,
      foodTruckOrMobileFoodUnit: false,
      commissaryOrBaseOfOperations: false,
      believesFoodExemptionMayApply: false,
      tentOrCanopy: true,
      tentSizeRange: "small-under-400-sq-ft",
      temporaryStageOrPlatform: false,
      cookingHeatSource: false,
      propaneOrFuelUse: false,
      streetClosure: false,
      sidewalkUseOrClosure: false,
      parkingLotUse: false,
      parkingSpacesBlocked: false,
      trafficControlNeeded: false,
      rightOfWayUse: false,
      alcoholPresent: false,
      alcoholSold: false,
      alcoholServedFree: false,
      alcoholByob: false,
      alcoholOnPublicProperty: false,
      temporarySignage: true,
      banners: false,
      ticketedEvent: false,
      admissionFee: false,
      publicAdvertising: true,
      cityParkOrFacility: true,
      privateProperty: false,
      publicProperty: true,
      venueOrPropertyOwnerPermission: true,
      indoorOrOutdoor: "outdoor",
      recurringEvent: false
    }
  }
];

export function listDemoScenarios() {
  return scenarios;
}

export function getDemoScenario(slug: string | null | undefined) {
  return scenarios.find((scenario) => scenario.slug === slug) ?? null;
}

export function getDemoResultsHref(scenario: DemoScenario) {
  return `/results?snapshot=${encodeScenarioSnapshot(scenario)}&demo=${scenario.slug}`;
}

export function getDemoGuidedHref(scenario: DemoScenario) {
  return `/intake?path=guided&demo=${scenario.slug}`;
}

export function getDemoDescribeHref(scenario: DemoScenario) {
  return `/intake?path=describe&demo=${scenario.slug}`;
}

function encodeScenarioSnapshot(scenario: DemoScenario) {
  const payload = serializeStoredIntakePayload(
    scenario.intake,
    scenario.eventFacts ?? intakeToEventFacts(scenario.intake)
  );
  return Buffer.from(payload, "utf8").toString("base64url");
}
