import type { IntakeInput } from "@/lib/schemas";

export const defaultIntakeValues: IntakeInput = {
  eventName: "",
  city: "phoenix",
  county: "Maricopa County",
  useCase: "retail-vendor-booth",
  eventType: "vendor-pop-up",
  propertyUse: "private-property",
  expectedAttendance: 75,
  vendorCount: 1,
  eventDate: "",
  recurrence: "one-time",
  hasFood: false,
  hasFoodTruck: false,
  hasRetailSales: true,
  hasAlcohol: false,
  hasAmplifiedSound: false,
  hasTemporaryStructure: false,
  hasGenerator: false,
  hasOpenFlame: false,
  hasStreetSidewalkOrParkingImpact: false,
  foodIsPrepackaged: false,
  foodIsOpenOrPreparedOnSite: false,
  foodRequiresTemperatureControl: false,
  foodSampling: false,
  drinksWithIceOrGarnish: false,
  foodTruckOrMobileFoodUnit: false,
  commissaryOrBaseOfOperations: false,
  believesFoodExemptionMayApply: false,
  tentOrCanopy: false,
  tentSizeRange: "none",
  temporaryStageOrPlatform: false,
  cookingHeatSource: false,
  propaneOrFuelUse: false,
  streetClosure: false,
  sidewalkUseOrClosure: false,
  parkingLotUse: false,
  parkingSpacesBlocked: false,
  trafficControlNeeded: false,
  rightOfWayUse: false,
  alcoholPresent: false,
  alcoholSold: false,
  alcoholServedFree: false,
  alcoholByob: false,
  alcoholOnPublicProperty: false,
  temporarySignage: false,
  banners: false,
  ticketedEvent: false,
  admissionFee: false,
  publicAdvertising: false,
  cityParkOrFacility: false,
  privateProperty: true,
  publicProperty: false,
  venueOrPropertyOwnerPermission: false,
  indoorOrOutdoor: "outdoor",
  recurringEvent: false
};
